// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';

// Load .env.local first (higher priority), then .env as fallback
config({ path: '.env.local' });
config({ path: '.env' });

import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // DIRECT_URL (session-mode, port 5432) cho migrations
    // Fallback sang DATABASE_URL nếu DIRECT_URL chưa set
    url: process.env['DIRECT_URL'] || process.env['DATABASE_URL'],
  },
});
