name = "man-chatbot"
main = "src/index.js"
compatibility_date = "2024-03-01"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "chat_db"
database_id = "e5c6610d-917e-48b3-8f6d-69edbce121d6"

[[vectorize]]
binding = "VECTORIZE"
index_name = "fpt-pricing-index"
